import { Vim } from "./Vim";

export default function App() {
  return (
    <Vim
      commands={[
        "--aljo",
        "i",
        ..."Hi,\n ",
        "Esc",
        "--cyan",
        "i",
        ..."Neon.",
        "Esc",
        "--aljo",
        1.5,
        "k",
        "dd",
        "dd",
        "--fontSize-4",
        "i",
        ..."A lot has\nhappened this year,\nhasn't it?",
        "Esc",
        1.5,
        "k",
        "k",
        "dd",
        "dd",
        "dd",
        "--fontSize-2",
        "i",
        ..."Your game with ",
        "Esc",
        "--pink",
        "a",
        ..."neon-ss",
        "Esc",
        "--aljo",
        "a",
        ..."\nwas pretty damn complicated\nfor both of us, lmao.",
        "Esc",
        1,
        "k",
        "k",
        "l",
        "v",
        "h",
        "d",
        "--pink",
        "i",
        ..."friend",
        "Esc",
        "--aljo",
        "a",
        ...", mb,",
        "Esc",
        2,
        "k",
        "k",
        "dd",
        "dd",
        "dd",
        "i",
        ..."You went through a shit ton of\nfeelings, thought you had it,\nthen you got depressed,\nand it was just a hell of a pain\nfor the whole year.",
        "Esc",
        2,
        "k",
        "k",
        "k",
        "k",
        "dd",
        "dd",
        "dd",
        "dd",
        "dd",
        "--fontSize-3",
        "i",
        ..."But it was so fun lmao,\ni'm not gonna lie",
        "Esc",
        1.5,
        "k",
        "dd",
        "dd",
        // "--fontSize-3",
        "i",
        ..."I'm glad to have\nsuffered with you,\nlmao.",
        "Esc",
        1.5,
        "k",
        "k",
        "dd",
        "dd",
        "dd",
        "--fontSize-2",
        "i",
        ..."And i believe you'll get ",
        "Esc",
        "--pink",
        "a",
        ..."neon-ss ",
        "Esc",
        "--aljo",
        "a",
        ..."\nsoon :)\n(Better get that shaver ready)",
        "Esc",
        1.5,
        "k",
        "k",
        "dd",
        "dd",
        "dd",
        "i",
        ..."And thanks for suffering\nwith me too, btw.\n",
        "Esc",
        0.5,
        "--yellow",
        "a",
        ..."aljo-ss",
        "Esc",
        "--aljo",
        "a",
        ..." is painful 😭",
        "Esc",
        1.5,
        "k",
        "k",
        "dd",
        "dd",
        "dd",
        "i",
        ..."I hope to see you ",
        "Esc",
        "--neonvim",
        "a",
        ..."Neonvim",
        "Esc",
        "--aljo",
        "a",
        ..." soon ;)",
        "Esc",
        1.5,
        "dd",
        "--fontSize-5",
        "i",
        ..."HAPPY BIRTHDAY,\n",
        "Esc",
        "--cyan",
        "a",
        ..."NEON",
        "Esc",
        "--aljo",
        "a",
        ..."!\n<3333",
        "Esc",
        2,
        "k",
        "k",
        "dd",
        "dd",
        "dd",
        "--white",
        "i",
        "-",
        0.5,
        "-",
        0.5,
        "-",
        0.5,
        "Esc",
        1,
        "dd",
        "i",
        ..."hey ",
        "Esc",
        "--cyan",
        "i",
        ..." Neon.",
        "Esc",
        1.2,
        "dd",
        "dd",
        "--white",
        "--fontSize-4",
        "i",
        ..."I had to cook this\non sudden notice...",
        "Esc",
        4.8,
        "k",
        "dd",
        "dd",
        "i",
        ..."I blame aljo,\nas usual.",
        "Esc",
        1,
        "k",
        "dd",
        "dd",
        "i",
        ..."can you imagine\nif you didn't leak\nthe server?",
        "Esc",
        1.4,
        "k",
        "dd",
        "k",
        "dd",
        "dd",
        "--fontSize-3",
        "i",
        ..."I wouldn't have been \nin ",
        "Esc",
        "--red",
        "i",
        ..." jadebetty's ",
        "Esc",
        "--white",
        "i",
        ..." server",
        "Esc",
        1.2,
        "k",
        "dd",
        "dd",
        "i",
        ..."heh, this message\nwouldn't be here.",
        "Esc",
        1.6,
        "k",
        "dd",
        "dd",
        "i",
        ..."from lyric spamming,\n",
        1.4,
        ..."to crying from aljo's\ncoding nonsense\n",
        "Esc",
        1.6,
        "k",
        "k",
        "dd",
        "dd",
        "dd",
        "i",
        ..."to practicing how to\nbecome chalant",
        "Esc",
        1.4,
        "k",
        "dd",
        "dd",
        "i",
        ..."pinging gabito for\nundertale perms,",
        "Esc",
        1.1,
        "k",
        "dd",
        "dd",
        "i",
        ..."and the random flirting.\nno homo tho - or I guess\n",
        1.1,
        ..."some homo ;)",
        "Esc",
        0.7,
        "k",
        "k",
        "dd",
        "dd",
        "dd",
        "i",
        ..."i know this is a\nbit short",
        "Esc",
        3,
        "k",
        "dd",
        "dd",
        "i",
        ..."but basically,\n",
        0.6,
        ..."in conclusion",
        "Esc",
        0.6,
        "k",
        "dd",
        "dd",
        "dd",
        "--green",
        "--fontSize-4",
        "i",
        ..."happy birthday !!",
        "Esc",
        3.8,
        "dd",
        "--pink",
        "--fontSize-2",
        "i",
        ..."you're cutest fucking blob ever <3",
        "Esc",
        3.8,
        "k",
        "dd",
        "dd",
        "--fontSize-5",
        "--white",
        "i",
        "-",
        0.5,
        "-",
        0.5,
        "-",
        0.5,
        "Esc",
        1,
        "dd",
        "--jade",
        "i",
        ..."neon",
        "Esc",
        1.6,
        "dd",
        "--fontSize-2",
        "i",
        ..."it's been a while since you\nwere invited here hasn't it?",
        "Esc",
        3.8,
        "k",
        "dd",
        "dd",
        "--fontSize-3",
        "i",
        ..."i never knew you\nleaked the invite to\nkeita 😀",
        "Esc",
        4.7,
        "k",
        "k",
        "dd",
        "dd",
        "dd",
        "--fontSize-2",
        "i",
        ..."it's been a year. i hope your life\nis fine now, dont worry\nabout neon-ss.",
        "Esc",
        6,
        "k",
        "k",
        "dd",
        "dd",
        "dd",
        "--fontSize-3",
        "i",
        ..."there are plenty of\nfishes in the sea",
        "Esc",
        3.2,
        "k",
        "dd",
        "dd",
        "i",
        ..."i have pictures of your\nfeet btw, remember when your\npc discoed?",
        "Esc",
        3,
        "k",
        "k",
        "dd",
        "dd",
        "dd",
        "--fontSize-2",
        "i",
        ..."you look beautiful as always.",
        "Esc",
        1.4,
        "dd",
        "i",
        ..."even tho i dont\nhave many IRL friends\nthat actually liked me, you do.",
        "Esc",
        3,
        "k",
        "k",
        "dd",
        "dd",
        "dd",
        "i",
        ..."you taught me a thing\nor two about typescript\ni never actually\nliked reading\nthe docs",
        "Esc",
        4,
        "k",
        "k",
        "k",
        "k",
        "dd",
        "dd",
        "dd",
        "dd",
        "dd",
        "i",
        ..."happy birthday, neon.",
        "Esc",
        5,
        "dd",
        "--fontSize-5",
        "--white",
        "i",
        "-",
        0.5,
        "-",
        0.5,
        "-",
        0.5,
        "Esc",
        1,
        "dd",
      ]}
    />
  );
}
